import type { CategoryId } from '../types/domain'

export const WORKSHOP_ANECDOTES = [
  '{lutin} a retrouvé son bonnet dans la boîte à biscuits.',
  'Un renne a mangé un coin du planning. Tout est quand même sous contrôle.',
  'Une bataille de boules de neige a éclaté pendant la pause. {lutin} a gagné !',
  '{lutin} a chanté si fort que les grelots se sont mis à danser.',
  'Le chocolat chaud avait une montagne de mousse ce matin.',
  'Un petit flocon s’est posé sur le nez de {lutin}. Atchoum !',
  'Les lutins ont formé une farandole entre les établis.',
  'Le renne Fripon a caché trois crayons sous sa paille.',
  '{lutin} a reçu un autocollant étoile pour son beau travail.',
  'La cloche du déjeuner a sonné deux fois. Personne ne s’est plaint.',
  'Un ruban doré s’est déroulé dans tout l’atelier comme un serpent.',
  '{lutin} a appris une nouvelle blague au Père Noël.',
  'Les souris de l’atelier ont apporté une miette de pain d’épices.',
  'Le vent a dessiné un cœur dans la neige devant la fenêtre.',
  'Un grelot perdu a été retrouvé dans la poche de {lutin}.',
  'Les lutins ont voté : aujourd’hui, les chaussettes rayées portent bonheur.',
  'Le grand réveil de l’atelier a sonné avec cinq minutes d’avance.',
  '{lutin} a partagé son dernier biscuit en forme d’étoile.',
  'Un renne a essayé de signer le registre avec son sabot.',
  'La neige brille si fort que tout l’atelier semble couvert de sucre.',
  'Les lutins ont construit un minuscule bonhomme de neige sur le rebord.',
  '{lutin} a trouvé une plume rouge et l’a glissée dans son bonnet.',
  'Le Père Noël est passé dire bonjour avec une tasse fumante.',
  'Une guirlande s’est allumée juste au moment où {prenom} a été nommé.',
  'Les marteaux ont joué un petit rythme de fête sur les établis.',
  '{lutin} a écrit “bravo” en lettres dorées sur le tableau.',
  'Un courant d’air a fait voler les listes comme des papillons.',
  'Les rennes se sont entraînés à marcher en cadence dans la cour.',
  'Une odeur de cannelle a rempli l’atelier pendant toute la matinée.',
  'Toute l’équipe a envoyé un grand coucou à {prenom}.',
] as const

export const LATE_GIFT_ANECDOTE = 'Ce souhait est arrivé tard : {lutin} et toute l’équipe font joyeusement des heures supplémentaires !'

export const CATEGORY_ANECDOTES: Record<CategoryId, readonly string[]> = {
  electronique: [
    '{lutin} a aligné les petits circuits comme une constellation.',
    'Les boutons ont réussi leur grand test de clics.',
    'Un voyant a clignoté trois fois pour dire bonjour à {prenom}.',
    'Les lutins-testeurs ont battu leur record sans tricher.',
    '{lutin} a démêlé tous les fils du premier coup. Presque tous !',
    'La batterie a fait le plein d’énergie de Noël.',
    'Le tournevis miniature de {lutin} a encore sauvé la journée.',
    'Les sons ont été réglés pour rester doux aux oreilles.',
    'Chaque bouton de {cadeau} a reçu son contrôle spécial.',
    'Un lutin a voulu tester encore une partie. Pour la science, bien sûr.',
    'Les circuits de {cadeau} brillent comme des petites étoiles.',
    '{lutin} a posé une étiquette “testé avec le sourire”.',
    'Le boîtier a passé le test des doigts pleins de chocolat.',
    'Le câble a été roulé en escargot parfait.',
    'Le coin électronique a applaudi quand le test s’est terminé.',
  ],
  peluche: [
    '{lutin} a choisi le tissu le plus doux de toute l’étagère.',
    'Le rembourrage de {cadeau} a gonflé comme un petit nuage.',
    'Trois câlins de contrôle ont été nécessaires. Quelle chance !',
    'Une couture chatouilleuse a fait rire {lutin}.',
    'Le ruban de {cadeau} a été noué avec deux jolies boucles.',
    'Les oreilles ont été vérifiées : elles sont parfaitement adorables.',
    '{lutin} a raconté une histoire pendant la séance de rembourrage.',
    'La machine à coudre a ronronné toute la matinée.',
    'Un flocon de tissu s’est posé sur le bonnet de {lutin}.',
    '{cadeau} a obtenu la meilleure note au test de douceur.',
    'Les boutons décoratifs ont été polis avec un mouchoir en soie.',
    'Le panier des fils colorés débordait comme un arc-en-ciel.',
    '{lutin} a vérifié deux fois que chaque couture était solide.',
    'La table des peluches ressemble aujourd’hui à un nuage géant.',
    'Un dernier câlin porte-bonheur a été ajouté pour {prenom}.',
  ],
  livre: [
    'Les pages de {cadeau} sentent bon le papier tout neuf.',
    '{lutin} a relu une phrase avec une voix de géant.',
    'Une virgule perdue a retrouvé sa place juste à temps.',
    'La couverture a reçu une pincée de poussière dorée.',
    'Les pages ont défilé comme les ailes d’un petit oiseau.',
    '{lutin} a testé le meilleur coin pour placer un marque-page.',
    'L’encre a séché près du poêle, bien au chaud.',
    'Le fil de la reliure a été noué avec grand soin.',
    'Un lutin a voulu lire la fin avant tout le monde. Motus !',
    '{cadeau} a passé le contrôle des pages bien rangées.',
    'Le marque-page rouge attend déjà {prenom}.',
    '{lutin} a soufflé doucement sur une minuscule poussière de papier.',
    'La presse à livres a fait “plouf” au lieu de “pouf”. Tout va bien.',
    'Les coins de la couverture sont maintenant bien protégés.',
    'Une histoire a fait sourire tout le coin des relieurs.',
  ],
  vehicule: [
    '{lutin} a fait tourner chaque roue avec un doigt expert.',
    'La piste d’essai avait un virage décoré de petits sapins.',
    'Les freins ont réussi le test du flocon surprise.',
    'Un grelot a servi de klaxon pendant quelques minutes.',
    'Les roues de {cadeau} roulent droit comme des champions.',
    '{lutin} a vérifié chaque vis avec sa loupe ronde.',
    'La direction a été réglée au millimètre près.',
    'Un renne a regardé l’essai depuis la barrière, très impressionné.',
    '{cadeau} a franchi la ligne d’arrivée sous les applaudissements.',
    'La pompe à air a sifflé un petit air de Noël.',
    '{lutin} a poli le châssis jusqu’à voir son reflet.',
    'La sonnette a fait dring exactement comme prévu.',
    'La piste enneigée a été balayée avant le grand essai.',
    'Chaque poignée a reçu le test des moufles.',
    'Le ruban de sécurité est prêt pour le voyage de {prenom}.',
  ],
  construction: [
    '{lutin} a trié les pièces par couleur sans en oublier une.',
    'La tour d’essai a tenu malgré un éternuement géant.',
    'Une petite brique s’était cachée sous le plan.',
    'Le modèle de {cadeau} a été monté puis démonté avec soin.',
    'Les pièces rouges ont gagné la course jusqu’à la boîte.',
    '{lutin} a compté deux fois. Puis une troisième, juste pour le plaisir.',
    'Les plans ont été déroulés sur la plus grande table.',
    'Un lutin a construit un minuscule tabouret pendant la pause.',
    'Toutes les pièces s’emboîtent avec un joli petit clic.',
    'La boîte de {cadeau} a réussi le test du grand secouage.',
    '{lutin} a ajouté un sachet bien rangé pour les petites pièces.',
    'Le coin construction avait des couleurs jusque sur les bonnets.',
    'Une arche d’essai a tenu toute seule pendant le goûter.',
    'Les instructions ont reçu de grands dessins très clairs.',
    'Le dernier comptage est parfait pour {prenom}.',
  ],
  'jeu-societe': [
    'Les lutins ont testé les règles autour d’une grande table ronde.',
    '{lutin} a lancé les dés et obtenu exactement ce qu’il fallait.',
    'Un pion s’était caché derrière la boîte de biscuits.',
    'La partie test de {cadeau} s’est terminée par un grand éclat de rire.',
    'Les cartes ont été mélangées par le champion officiel du mélange.',
    'Le plateau est bien à plat, même avec des moufles.',
    '{lutin} a vérifié que la règle la plus rigolote était facile à comprendre.',
    'Les dés ont été polis jusqu’à briller sous les guirlandes.',
    'Une équipe de rennes a voulu participer à la partie.',
    'Tous les pions de {cadeau} sont bien au chaud dans leur sachet.',
    'Le sablier a été testé sans perdre un seul grain.',
    '{lutin} a déclaré la partie “amusante et approuvée”.',
    'Les cartes ont reçu des coins tout doux.',
    'Le score final est resté secret pour éviter les jaloux.',
    'La boîte se ferme parfaitement pour le voyage vers {prenom}.',
  ],
  'poupee-figurine': [
    '{lutin} a dessiné le sourire avec son pinceau le plus fin.',
    'Les couleurs de {cadeau} ont séché près d’une guirlande chaude.',
    'Un minuscule accessoire avait roulé sous l’établi.',
    'Chaque détail a été observé avec une loupe en forme d’étoile.',
    'Les articulations ont fait leur gymnastique du matin.',
    '{lutin} a choisi une couleur qui brille juste comme il faut.',
    'Le personnage a tenu debout pendant tout le test.',
    'Un petit pinceau s’est retrouvé avec de la peinture sur le manche.',
    'La tenue de {cadeau} a reçu un dernier pli bien net.',
    'Les accessoires ont chacun leur place dans la boîte.',
    '{lutin} a raconté une aventure au personnage pendant le contrôle.',
    'Le modelage des détails est terminé sans aucune bosse.',
    'Une étoile a été peinte sous le socle pour porter bonheur.',
    'Le coin des figurines a organisé un défilé improvisé.',
    '{cadeau} est prêt à imaginer mille histoires avec {prenom}.',
  ],
  'vetement-accessoire': [
    '{lutin} a déroulé le tissu sur une table longue comme un traîneau.',
    'Le fil assorti était caché juste derrière une bobine dorée.',
    'Les coutures de {cadeau} sont droites et bien solides.',
    'Un mannequin lutin a pris une pose très sérieuse pour l’essayage.',
    'Chaque bouton a été vérifié avec des doigts experts.',
    '{lutin} a repassé un petit pli qui faisait le malin.',
    'La matière a réussi le grand test de douceur.',
    'Une étiquette confortable a été préparée pour {prenom}.',
    'Les ciseaux ont fait snip-snip au rythme des grelots.',
    'Le ruban de mesure s’est enroulé autour du bonnet de {lutin}.',
    'Les finitions de {cadeau} ont reçu une étoile dorée.',
    'La couleur paraît encore plus belle près de la neige.',
    '{lutin} a vérifié que rien ne gratte ni ne chatouille.',
    'Une poche a été testée avec un biscuit. Elle fonctionne !',
    'Le pliage final est aussi net qu’un paquet cadeau.',
  ],
  sport: [
    '{lutin} a échauffé ses bras avant le grand test.',
    'Le matériel de {cadeau} a réussi l’épreuve des trois rebonds.',
    'Un renne a joué le rôle d’arbitre depuis la barrière.',
    'Les réglages ont été adaptés avec beaucoup de précision.',
    '{lutin} a marqué un point et fait une danse de victoire.',
    'La poignée a passé le test des petites mains et des moufles.',
    'Le terrain d’essai a été tracé dans la neige fraîche.',
    'Tous les lacets et attaches sont bien solides.',
    'Le sifflet de départ a surpris un lutin qui buvait son chocolat.',
    '{cadeau} est bien équilibré pour de belles aventures.',
    'L’équipe sportive a donné la note maximale au contrôle.',
    '{lutin} a nettoyé une dernière trace de neige.',
    'Le record du jour a été inscrit au tableau rouge.',
    'Les protections ont été vérifiées une par une.',
    'Toute l’équipe encourage déjà {prenom}.',
  ],
  'loisirs-creatifs': [
    '{lutin} a rangé les couleurs comme un arc-en-ciel.',
    'Un pinceau a dessiné une moustache sur une feuille de brouillon.',
    'Les crayons de {cadeau} ont tous une pointe parfaite.',
    'La peinture a réussi le test du joli mélange.',
    '{lutin} a fabriqué une minuscule étoile pendant la pause.',
    'Les perles ont été comptées sans en laisser rouler une seule.',
    'Le papier coloré craque doucement comme la neige.',
    'Une idée surprise a été glissée dans le coffret.',
    'Les feutres ont défilé pour montrer toutes leurs couleurs.',
    '{cadeau} a reçu une protection spéciale contre les petites taches.',
    '{lutin} a testé la colle sur deux morceaux de papier doré.',
    'Les ciseaux sont prêts à découper des formes rigolotes.',
    'Le coin créatif brillait de mille couleurs cet après-midi.',
    'Chaque outil a retrouvé sa place dans le coffret.',
    'Une carte blanche attend la première idée de {prenom}.',
  ],
  mystere: [
    '{lutin} a fermé le grand rideau rouge avant de commencer.',
    'Les plans secrets ont été rangés dans une enveloppe étoilée.',
    'Un grelot spécial a sonné derrière la porte interdite.',
    'Trois lutins ont chuchoté puis éclaté de rire.',
    'La machine mystérieuse a fait “plim” exactement comme prévu.',
    '{lutin} a utilisé une clé dorée réservée aux grands secrets.',
    'Un nuage de paillettes s’est échappé de l’atelier caché.',
    'Le Père Noël a vérifié les plans avec un grand sourire.',
    'Une boîte sans étiquette a traversé le couloir sur la pointe des pieds.',
    'Les lutins ont juré de ne rien révéler à {prenom}.',
    'Le rideau a bougé, mais ce n’était qu’un courant d’air. Peut-être.',
    '{lutin} a coché une case avec son crayon le plus secret.',
    'La salle spéciale est restée fermée pendant toute la pause.',
    'Un ruban doré attend dans un tiroir marqué “chut”.',
    'Tout avance parfaitement, mais les lutins gardent la surprise.',
  ],
}
